name: Go
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13.8
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.8

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/displague/github-labeller

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/github-labeller/go

    - name: Get Module
      run: GO111MODULE=off go get github.com/displague/github-labeller
      env:
        GOPATH: /home/runner/work/github-labeller/go

    # Run testing on the code
    - name: Install Repo Labeller
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} github-labeller TeraTech-Uganda
      env:
        GOPATH: /home/runner/work/github-labeller/go
